<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\Shared\ZipArchive;


class wordController extends Controller
{
    public function createWordDocument($id)
    {

        $phpWord = new PhpWord();
        $section = $phpWord->addSection();
        $section->addText('Hello, this is a sample Word document generated by Laravel! '.$id);


        $fileName = 'sample-word-file.docx';
        $tempFile = tempnam(sys_get_temp_dir(), $fileName);
        $objWriter = IOFactory::createWriter($phpWord, 'Word2007');
        $objWriter->save($tempFile);
        return response()->download($tempFile, $fileName)->deleteFileAfterSend(true);
    }
}
